# Generated by Django 4.2.4 on 2023-08-31 04:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_alter_comment_post_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_user',
            field=models.ManyToManyField(related_name='like_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
